// <auto-generated />
namespace tlogNew.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class manytomany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(manytomany));
        
        string IMigrationMetadata.Id
        {
            get { return "201911130745300_manytomany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
